-- Create ICD-10 Codes table
CREATE TABLE IF NOT EXISTS icd10_codes (
    code VARCHAR(10) PRIMARY KEY,
    description TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed common ICD-10 codes
INSERT INTO icd10_codes (code, description) VALUES
('A00', 'Cholera'),
('A01', 'Typhoid and paratyphoid fevers'),
('A09', 'Infectious gastroenteritis'),
('B20', 'Human immunodeficiency virus [HIV] disease'),
('B24', 'Unspecified human immunodeficiency virus [HIV] disease'),
('B50', 'Plasmodium falciparum malaria'),
('B51', 'Plasmodium vivax malaria'),
('B97.2', 'Coronavirus as the cause of diseases classified elsewhere'),
('E03', 'Other hypothyroidism'),
('E05', 'Thyrotoxicosis [hyperthyroidism]'),
('E10', 'Type 1 diabetes mellitus'),
('E11', 'Type 2 diabetes mellitus'),
('G40', 'Epilepsy and recurrent seizures'),
('G43', 'Migraine'),
('G44', 'Other headache syndromes'),
('H10', 'Conjunctivitis'),
('I10', 'Essential (primary) hypertension'),
('I20', 'Angina pectoris'),
('I21', 'Acute myocardial infarction'),
('I50', 'Heart failure'),
('J00', 'Acute nasopharyngitis [common cold]'),
('J01', 'Acute sinusitis'),
('J02', 'Acute pharyngitis'),
('J03', 'Acute tonsillitis'),
('J18', 'Pneumonia, unspecified organism'),
('J44', 'Other chronic obstructive pulmonary disease'),
('J45', 'Asthma'),
('K21', 'Gastro-esophageal reflux disease'),
('K29', 'Gastritis and duodenitis'),
('K35', 'Acute appendicitis'),
('K80', 'Cholelithiasis'),
('M05', 'Seropositive rheumatoid arthritis'),
('M15', 'Polyosteoarthritis'),
('M54', 'Dorsalgia (Back pain)'),
('N17', 'Acute kidney failure'),
('N18', 'Chronic kidney disease'),
('N39', 'Urinary tract infection, site not specified'),
('O80', 'Encounter for full-term uncomplicated delivery'),
('O82', 'Encounter for cesarean delivery by specified case'),
('R05', 'Cough'),
('R06', 'Abnormalities of breathing'),
('R07', 'Pain in throat and chest'),
('R10', 'Abdominal and pelvic pain'),
('R11', 'Nausea and vomiting'),
('R50', 'Fever of other and unknown origin'),
('R51', 'Headache'),
('R52', 'Pain, unspecified'),
('S00', 'Superficial injury of head'),
('S01', 'Open wound of head'),
('S02', 'Fracture of skull and facial bones'),
('T14', 'Injury of unspecified body region'),
('U07.1', 'COVID-19'),
('Z00', 'Encounter for general examination without complaint'),
('Z30', 'Encounter for contraceptive management')
ON CONFLICT (code) DO NOTHING;
